platform :ios, '9.0'

target 'Finder' do
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'RSKImageCropper'
  pod 'QBImagePickerController'
  pod 'Firebase/Storage'
  # lines below is not working yet
  # pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
  # pod 'react-native-fetch-blob', :path => '../node_modules/react-native-fetch-blob'

end