platform :ios, '9.0'

target 'Finder' do
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  # this line below is not working yet
  # pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

end